      // swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ARchitect",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "ARchitect",
            targets: ["AppModule"],
            bundleIdentifier: "com.svetrivel.ARchitect.v1",
            teamIdentifier: "4TJJL53F39",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "ARchitect needs camera access to display AR content.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            exclude: [
                "Package.swift",
                "README.md",
                "Info.plist",
                ".gitignore"
            ]
        )
    ],
    swiftLanguageVersions: [.v6]
)
