// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Nebula",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Nebula",
            targets: ["AppModule"],
            bundleIdentifier: "com.svetrivel.Nebula",
            teamIdentifier: "4TJJL53F39",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Nebula needs camera access to display AR content.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            exclude: ["Package.swift", "README.md", "Info.plist", ".gitignore"]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)